name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    env:
      # Define the solution file path relative to the repository root
      SOLUTION_FILE_PATH: 'WPF Extended DataGrid 2022/WpfControlKit DataGrid 2022.sln'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install NuGet CLI
        run: choco install nuget.commandline

      - name: Increment version in AssemblyInfo.cs
        run: |
          $files = Get-ChildItem -Path . -Filter AssemblyInfo.cs -Recurse
          foreach ($file in $files) {
            (Get-Content $file.PSPath) -replace 'AssemblyVersion\("(\d+\.\d+\.\d+\.)(\d+)"\)', 'AssemblyVersion("$1$($2 + 1)")' | Set-Content $file.PSPath
            (Get-Content $file.PSPath) -replace 'AssemblyFileVersion\("(\d+\.\d+\.\d+\.)(\d+)"\)', 'AssemblyFileVersion("$1$($2 + 1)")' | Set-Content $file.PSPath
          }

      - name: Commit version increment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Incremented build number"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin HEAD:main

      - name: Restore dependencies
        run: nuget restore "${{ env.SOLUTION_FILE_PATH }}"

      - name: Build
        run: |
          $msbuild = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe"
          & $msbuild "${{ env.SOLUTION_FILE_PATH }}" /p:Configuration=Release

      - name: Pack
        run: |
          nuget pack "WPF Extended DataGrid 2022/ExtendedGrid/ExtendedGrid.csproj" -Prop Configuration=Release -OutputDirectory ./output
          dir ./output

      - name: Set up NuGet for GitHub Packages
        run: |
          nuget sources Add -Name "GitHub" -Source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" -Username ${{ github.actor }} -Password ${{ secrets.NUGET_API_KEY }}

      - name: Publish to GitHub Packages
        run: |
          $package = Get-ChildItem -Path ./output -Filter *.nupkg | Select-Object -First 1
          nuget push $package.FullName -Source "GitHub" -ApiKey ${{ secrets.NUGET_API_KEY }}
