name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    env:
      SOLUTION_FILE_PATH: 'WPF Extended DataGrid 2022/WpfControlKit DataGrid 2022.sln'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install NuGet CLI
        run: choco install nuget.commandline
      
      - name: Increment version in AssemblyInfo.cs
        shell: pwsh
        run: |
          $files = Get-ChildItem -Path . -Filter AssemblyInfo.cs -Recurse
          foreach ($file in $files) {
            $content = Get-Content $file.PSPath
            $updatedContent = @()

            foreach ($line in $content) {
              if ($line -match 'AssemblyVersion\("(\d+)\.(\d+)\.(\d+)\.(\d+)"\)') {
                $major = $matches[1]
                $minor = $matches[2]
                $build = [int]$matches[3] + 1  # Increment the build number
                $revision = $matches[4]
                $newLine = "[assembly: AssemblyVersion(`"$major.$minor.$build.$revision`")]"
                Write-Output "Updated AssemblyVersion: $newLine"
                $updatedContent += $newLine
              }
              elseif ($line -match 'AssemblyFileVersion\("(\d+)\.(\d+)\.(\d+)\.(\d+)"\)') {
                $major = $matches[1]
                $minor = $matches[2]
                $build = [int]$matches[3] + 1  # Increment the build number
                $revision = $matches[4]
                $newLine = "[assembly: AssemblyFileVersion(`"$major.$minor.$build.$revision`")]"
                Write-Output "Updated AssemblyFileVersion: $newLine"
                $updatedContent += $newLine
              }
              else {
                $updatedContent += $line
              }
            }

            # Save the modified content back to the file
            Set-Content -Path $file.PSPath -Value $updatedContent
            Write-Output "Updated file: $file"
          }





      - name: Commit version increment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Incremented build number"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin HEAD:main

      - name: Restore dependencies
        run: nuget restore "${{ env.SOLUTION_FILE_PATH }}"

      - name: Build
        run: |
          $msbuild = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe"
          & $msbuild "${{ env.SOLUTION_FILE_PATH }}" /p:Configuration=Release

      - name: Pack
        run: |
          nuget pack "WPF Extended DataGrid 2022/ExtendedGrid/ExtendedGrid.csproj" -Properties Configuration=Release -OutputDirectory ./output
          dir ./output

      - name: Publish to NuGet.org
        run: |
          $package = Get-ChildItem -Path ./output -Filter *.nupkg | Select-Object -First 1
          nuget push $package.FullName -Source "https://api.nuget.org/v3/index.json" -ApiKey ${{ secrets.NUGET_API_KEY }}
