name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    env:
      # Define the solution file path relative to the repository root
      SOLUTION_FILE_PATH: 'WPF Extended DataGrid 2022/WpfControlKit DataGrid 2022.sln'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Framework
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '4.8.x' # Use this to specify the .NET SDK version that supports .NET Framework 4.8

      - name: Install NuGet CLI
        run: choco install nuget.commandline

      - name: Restore dependencies
        run: nuget restore ${{ env.SOLUTION_FILE_PATH }}

      - name: Build
        run: msbuild ${{ env.SOLUTION_FILE_PATH }} /p:Configuration=Release

      - name: Pack
        run: nuget pack "WPF Extended DataGrid 2022/ExtendedGrid/ExtendedGrid.csproj" -Prop Configuration=Release -OutputDirectory ./output

      - name: Publish to GitHub Packages
        run: nuget push ./output/*.nupkg -Source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" -ApiKey ${{ secrets.GITHUB_TOKEN }}
