name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    env:
      # Define the solution file path relative to the repository root
      SOLUTION_FILE_PATH: 'WPF Extended DataGrid 2022/WpfControlKit DataGrid 2022.sln'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install NuGet CLI
        run: choco install nuget.commandline

      - name: Restore dependencies
        run: nuget restore "${{ env.SOLUTION_FILE_PATH }}"

      - name: Build
        run: |
          $msbuild = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe"
          & $msbuild "${{ env.SOLUTION_FILE_PATH }}" /p:Configuration=Release

      - name: Pack
        run: |
          nuget pack "WPF Extended DataGrid 2022/ExtendedGrid/ExtendedGrid.csproj" -Prop Configuration=Release -OutputDirectory ./output
          ls ./output

      - name: Set up NuGet for GitHub Packages
        run: |
          nuget sources Add -Name "GitHub" -Source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" -Username ${{ github.actor }} -Password ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        run: |
          ls ./output/*.nupkg
          nuget push "D:\a\WpfExtendedDataGrid\WpfExtendedDataGrid\output\ExtendedGrid.4.8.0.nupkg" -Source "GitHub"
