name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    env:
      # Define the solution file path relative to the repository root
      SOLUTION_FILE_PATH: 'WPF Extended DataGrid 2022/WpfControlKit DataGrid 2022.sln'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install NuGet CLI
        run: choco install nuget.commandline

      - name: Restore dependencies
        run: nuget restore "${{ env.SOLUTION_FILE_PATH }}"

      - name: Build
        run: |
          $msbuild = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe"
          & $msbuild "${{ env.SOLUTION_FILE_PATH }}" /p:Configuration=Release

      - name: Pack
        run: |
          nuget pack "WPF Extended DataGrid 2022/ExtendedGrid/ExtendedGrid.csproj" -Prop Configuration=Release -OutputDirectory ./output
          dir ./output

      - name: Set up NuGet for NuGet.org
        run: |
          nuget sources Add -Name "NuGet.org" -Source "https://api.nuget.org/v3/index.json" -Username ${{ github.actor }} -Password ${{ secrets.NUGET_API_KEY }}

      - name: Publish to NuGet.org
        run: |
          $package = Get-ChildItem -Path ./output -Filter *.nupkg | Select-Object -First 1
          nuget push $package.FullName -Source "https://api.nuget.org/v3/index.json" -ApiKey ${{ secrets.NUGET_API_KEY }}
